import ctypes
from PyQt5 import QtCore, QtGui, QtWidgets
import keyboard

class Ui_MainWindow(object):
    def __init__(self):
        self.Trigger = False
        self.Wallhack = False
        self.Bhop = False
        self.Noflash = False
        self.Togglefov = False
        self.Triggerkey = ""
        self.Fov = False
        self.Fovkey = ""
        self.Radar = False
        self.Aimbot = False
        self.Silentaim = False
        self.Baim = False
        self.Fovt = int()
        self.auto_strafe = False
        self.Ergb = [0, 0, 0]
        self.Argb = [0, 0, 0]
        self.Allies = False
        self.Enemies = False
        self.Healthbased = False
        self.RCS = False
        self.AimRCS = False
        self.Aimfov = int()
        self.Fovvaluke = int()
        self.Aimbotkey = str()
        self.Holdfov = False
        self.Eteam = False
        self.Chams = False
        self.spotted = False
    def update(self):
        update = True
        while update:
            self.Wallhack = self.checkBox.isChecked()
            self.Chams = self.checkBox_2.isChecked()
            self.Noflash = self.checkBox_3.isChecked()
            self.Enemies = self.checkBox_4.isChecked()
            self.Allies = self.checkBox_5.isChecked()
            if self.comboBox.currentText() == "GREEN":
                self.Ergb = [0,255,0]
            elif self.comboBox.currentText() == "RED":
                self.Ergb = [255,0,0]
            elif self.comboBox.currentText() == "BLUE":
                self.Ergb = [0,0,255]
            elif self.comboBox.currentText() == "ORANGE":
                self.Ergb = [255,69, 0]
            if self.comboBox_2.currentText() == "GREEN":
                self.Argb = [0,255,0]
            elif self.comboBox_2.currentText() == "RED":
                self.Argb = [255,0,0]
            elif self.comboBox_2.currentText() == "BLUE":
                self.Argb = [0,0,255]
            elif self.comboBox_2.currentText() == "ORANGE":
                self.Argb = [255,69,0]
            self.Radar = self.checkBox_6.isChecked()
            self.Aimbot = self.checkBox_7.isChecked()
            self.AimRCS = self.checkBox_8.isChecked()
            self.Silentaim = self.checkBox_9.isChecked()
            self.Baim = self.checkBox_10.isChecked()
            self.Aimfov = int(self.lineEdit.text())
            self.spotted = self.checkBox_12.isChecked()
            self.Trigger = self.checkBox_13.isChecked()
            self.Aimbotkey = self.lineEdit_2.text().lower()
            self.RCS = self.checkBox_11.isChecked()
            self.Holdfov = self.checkBox_15.isChecked()
            self.Fovvaluke = int(self.lineEdit_3.text())
            self.Bhop = self.checkBox_16.isChecked()
            self.auto_strafe = self.checkBox_17.isChecked()
            self.Fov = self.checkBox_18.isChecked()
            self.Fovkey = self.lineEdit_5.text()
            self.Triggerkey = self.lineEdit_4.text()
            if self.Aimbot and not keyboard.is_modifier(self.Aimbotkey):
                ctypes.windll.user32.MessageBoxW(0,"Please enter an valid Aimbot Key", "Error in Config",1)
            if self.Silentaim and not self.Aimbot:
                ctypes.windll.user32.MessageBoxW(0,"Select Aimbot if you wanna use Silentaim", "Error in Config", 1)

            update = False


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 493)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 861, 481))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.tabWidget.setFont(font)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.checkBox = QtWidgets.QCheckBox(self.tab)
        self.checkBox.setGeometry(QtCore.QRect(50, 70, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_2.setGeometry(QtCore.QRect(50, 120, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_3.setGeometry(QtCore.QRect(50, 260, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_4.setGeometry(QtCore.QRect(80, 160, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_5.setGeometry(QtCore.QRect(80, 200, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(280, 160, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(280, 200, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_6.setGeometry(QtCore.QRect(50, 310, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName("checkBox_6")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(200, 370, 211, 51))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.checkBox_7 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_7.setGeometry(QtCore.QRect(50, 60, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_8.setGeometry(QtCore.QRect(80, 100, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_9.setGeometry(QtCore.QRect(80, 140, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_10.setGeometry(QtCore.QRect(80, 180, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_10.setFont(font)
        self.checkBox_10.setObjectName("checkBox_10")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit.setGeometry(QtCore.QRect(80, 230, 51, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.tab_4)
        self.label.setGeometry(QtCore.QRect(140, 230, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.checkBox_12 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_12.setGeometry(QtCore.QRect(80, 280, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_12.setFont(font)
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_13.setGeometry(QtCore.QRect(390, 60, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_13.setFont(font)
        self.checkBox_13.setObjectName("checkBox_13")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 320, 171, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.checkBox_11 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_11.setGeometry(QtCore.QRect(390, 170, 141, 21))
        self.checkBox_11.setObjectName("checkBox_11")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 370, 211, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_4.setGeometry(QtCore.QRect(390, 110, 201, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.checkBox_15 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_15.setGeometry(QtCore.QRect(80, 110, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_15.setFont(font)
        self.checkBox_15.setObjectName("checkBox_15")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(80, 150, 51, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.checkBox_16 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_16.setGeometry(QtCore.QRect(50, 250, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_16.setFont(font)
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_17.setGeometry(QtCore.QRect(50, 300, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_17.setFont(font)
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_18.setGeometry(QtCore.QRect(50, 60, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox_18.setFont(font)
        self.checkBox_18.setObjectName("checkBox_18")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 370, 211, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_5.setGeometry(QtCore.QRect(80, 190, 121, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(210, 190, 151, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(210, 150, 151, 31))
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox.setText(_translate("MainWindow", "GLOW"))
        self.checkBox_2.setText(_translate("MainWindow", "CHAMS"))
        self.checkBox_3.setText(_translate("MainWindow", "NOFLASH"))
        self.checkBox_4.setText(_translate("MainWindow", "ENEMIES"))
        self.checkBox_5.setText(_translate("MainWindow", "TEAMMATES"))
        self.comboBox.setItemText(0, _translate("MainWindow", "GREEN"))
        self.comboBox.setItemText(1, _translate("MainWindow", "RED"))
        self.comboBox.setItemText(2, _translate("MainWindow", "BLUE"))
        self.comboBox.setItemText(3, _translate("MainWindow", "ORANGE"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "GREEN"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "RED"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "BLUE"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "ORANGE"))
        self.checkBox_6.setText(_translate("MainWindow", "RADAR"))
        self.pushButton.setText(_translate("MainWindow", "UPDATE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "VISUALS"))
        self.checkBox_7.setText(_translate("MainWindow", "AIMBOT"))
        self.checkBox_8.setText(_translate("MainWindow", "RCS WITH AIMBOT"))
        self.checkBox_9.setText(_translate("MainWindow", "SILENTAIM"))
        self.checkBox_10.setText(_translate("MainWindow", "BODY AIM"))
        self.lineEdit.setText(_translate("MainWindow", "120"))
        self.label.setText(_translate("MainWindow", "AIMBOT FOV"))
        self.checkBox_12.setText(_translate("MainWindow", "ONLY SPOTTED"))
        self.checkBox_13.setText(_translate("MainWindow", "TRIGGERBOT"))
        self.lineEdit_2.setText(_translate("MainWindow", "AIMBOT KEY"))
        self.checkBox_11.setText(_translate("MainWindow", "RCS"))
        self.pushButton_2.setText(_translate("MainWindow", "UPDATE"))
        self.lineEdit_4.setText(_translate("MainWindow", "TRIGGERBOT KEY"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "AIM"))
        self.checkBox_15.setText(_translate("MainWindow", "HOLD TO CHANGE FOV"))
        self.lineEdit_3.setText(_translate("MainWindow", "120"))
        self.checkBox_16.setText(_translate("MainWindow", "BHOP"))
        self.checkBox_17.setText(_translate("MainWindow", "AUTO STRAFE"))
        self.checkBox_18.setText(_translate("MainWindow", "FOV CHANGER"))
        self.pushButton_3.setText(_translate("MainWindow", "UPDATE"))
        self.lineEdit_5.setText(_translate("MainWindow", "c"))
        self.label_2.setText(_translate("MainWindow", "FOV KEY"))
        self.label_3.setText(_translate("MainWindow", "FOV VALUE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "MISC"))
        self.pushButton.clicked.connect(self.update)
        self.pushButton_2.clicked.connect(self.update)
        self.pushButton_3.clicked.connect(self.update)
